version: '2'
services:
  apache:
    links:
      - wildfly
    build:
      context: ./apache
      args:
        link: 'wildfly'
    expose:
      - "80"
      - "443"
    ports:
      - "81:80"
      - "4431:443"
  wildfly:
    build: ./wildfly
    expose:
      - "8009"
      - "8080"
      - "8443"
      - "9990"
    ports:
      - "28009:8009"
      - "28080:8080"
      - "28443:8443"
      - "29990:9990"
